// src/app/layout.tsx
import type { Metadata } from "next";
// 1. 确保引入了字体
import { Oswald, JetBrains_Mono } from "next/font/google"; 
import "./globals.css";

// 2. 配置字体对象
const oswald = Oswald({ 
  subsets: ["latin"], 
  variable: "--font-oswald", // 这个变量名必须和 tailwind.config.ts 里的一致
  display: "swap",
});

const jetbrains = JetBrains_Mono({ 
  subsets: ["latin"], 
  variable: "--font-jetbrains",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Endfield Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // 3. 关键点：将变量注入到 html 标签，并添加 font-sans 类
    <html lang="en" className={`${oswald.variable} ${jetbrains.variable}`}>
      <body className="font-sans antialiased">
        <div className="noise-bg" />
        {children}
      </body>
    </html>
  );
}